# Generated by Django 5.2.8 on 2025-12-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
